### ISSUE TITLE
Error Installing Library (Ticket Evolution)

### ISSUE THREAD

**Issue by vtankaria** [ticketevolution/ticketevolution-php#119]
Hello, 

I downloaded ticketevolution-php-master zip, extracted it and followed the steps to install it.

"curl -sS https://getcomposer.org/installer | php" this created the composer.phar file successfully. 

then I executed the following command : php composer.phar require ticketevolution/ticketevolution-php:~2.2

But this threw an error, as listed below. 

./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package ticketevolution/ticketevolution-php 1.0.0 could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

Can you please help us with the installation ? What can be the issue ? 

Thank You.

**Comment by vtankaria** [comment]
Hello , 
Instead of php composer.phar require ticketevolution/ticketevolution-php:~2.2 we used 
php composer.phar require ticketevolution/ticketevolution-php:~1.0.0 and the installation was successful.

Now I created a php file in library folder and here the code in it :

require '../vendor/autoload.php';
$cfg['params']['apiToken'] = (string) 'bb16c585e54d83e5c1ac03720508f3ba';
$cfg['params']['secretKey'] = (string) '58YCJpx4EowtweBY/rT5l7d4CPtRtIywWeo4evss';
$tevo = new Ticketevolution\Webservice($cfg['params']);
print_r($tevo);

It gives me a fatal error : 
PHP Fatal error:  Class 'Ticketevolution\Webservice' not found in /var/www/html/ticevol/library/mycode.php on line 5

What could be the issue. I followed steps given here : https://github.com/ticketevolution/ticketevolution-php/blob/master/Documentation.md.

kindly help

**Comment by vtankaria** [comment]
Hello,

Installation worked when  ticketevolution/ticketevolution-php:~2.2 was changed to icketevolution/ticketevolution-php 1.0.0 and executed

**Comment by vtankaria** [comment]
Hello,

I am using the library and trying to createOrder : here is the code

$arr = array('orders' => array
		    (
			  'shipped_items' => array
					    (
						  'items' => array
							  (
								  'ticket_group_id' => 177389023,
								  'price' => 18,
								  'quantity' => 2
							  )
					    ),
			  'payments' => array
					(
					      "type" => "offline"
					),
			  'seller_id' => '1883',
			  'client_id' => 117838
	      )
	);

$results = $tevo->createOrders($arr);

print_r($results);

It gives me error :

PHP Fatal error:  Uncaught exception 'TicketEvolution\ApiException' in /var/www/html/ticevol/library/TicketEvolution/Webservice.php:2521
Stack trace:
#0 /var/www/html/ticevol/library/TicketEvolution/Webservice.php(2467): TicketEvolution\Webservice->_handleApiError('<!DOCTYPE html>...', 500, NULL)
#1 /var/www/html/ticevol/library/TicketEvolution/Webservice.php(1527): TicketEvolution\Webservice->_postProcess(Object(Zend_Http_Response))
#2 /var/www/html/ticevol/library/mycode.php(38): TicketEvolution\Webservice->createOrders(Array)
#3 {main}
  thrown in /var/www/html/ticevol/library/TicketEvolution/Webservice.php on line 2521


While i used the Performer sample code : It worked Fine.

$options = array('page' => 1,
                 'per_page' => 10);

$results = $tevo->searchPerformers('Chris', $options);

foreach ($results as $performer) {
    echo $performer->name . '<br />' . PHP_EOL;
}

I'm using Sandbox version . What can be the issue. kindly help for the same. Thank you

**Comment by jwcobb** [comment]
I'm not sure what version you actually have installed at this point. You should be using either 2.2.2 or 3.0RC1. I would recommend that you use the 3.0 as the only thing that I see changing in it is the Laravel integration.

Can you tell me which version you ended up getting installed?

**Comment by jwcobb** [comment]
As for your issue with createOrder, please open a support ticket at support@ticketevolution.com and identify which company you are working on behalf of.
