### ISSUE TITLE
Branch naming

### ISSUE THREAD

**Issue by ppavel** [ticketevolution/ticketevolution-php#120]
Hello jwcobb!

Composer has known issue/feature with '3.0' naming.
"- The requested package ticketevolution/ticketevolution-php dev-3.0 could not be found."

Could you please create a copy of 3.0 branch named, say, "third"?

**Comment by jwcobb** [comment]
I'm just gonna bump 3.0 to be an official release.

**Comment by jwcobb** [comment]
I'll do the version bump later today, but in the meantime this does work in your `composer.json`

    "require": {
        "ticketevolution/ticketevolution-php": "~3.0-dev"
    }
