### ISSUE TITLE
ticketevolution-php not compatible with Laravel 5.1.11

### ISSUE THREAD

**Issue by sonnygauran** [ticketevolution/ticketevolution-php#123]
I tried installing the libraray via instructions indicated at _Installation for Laravel 5_ indicated at [`Documentation.md`](https://github.com/ticketevolution/ticketevolution-php/blob/master/Documentation.md#installation-for-laravel-5). However, the current version of `guzzlehttp/guzzle` is at `^6.0` which is incompatible with the _Event system_ of [`guzzlehttp/guzzle:~5.0`](https://github.com/guzzle/guzzle/blob/master/UPGRADING.md#migrating-to-middleware).

**Comment by sonnygauran** [comment]
Do you have any plans for updating the library with `guzzlehttp/guzzle:^6.0`?

**Comment by jwcobb** [comment]
ticketevolution-php currently relies on [guzzle/guzzle-services](https://github.com/guzzle/guzzle-services) which has not yet been updated for use with Guzzle 6.

It appears that @jeremeamia [might be taking over the guzzle-services project](https://twitter.com/mtdowling/status/613087067816480768) but I do not think that has been confirmed and even if he does he has stated he won’t be working on any OSS projects until after the [PHPNW conference](http://pnwphp.com/), which happens to take place later this week.

I'd like to get a better idea if guzzle-services will be updated for Guzzle 6 before taking any action, but would be open to a PR as well.


Does [Guzzle5's custom Event system](http://guzzle.readthedocs.org/en/5.3/events.html) somehow clash with Laravel’s?

**Comment by sonnygauran** [comment]
I have an existing project which previously depends on `guzzlehttp/guzzle:^6.0` which won't match with the library's dependency.

But on an independent Laravel 5.1.11 project it worked flawlessly, thank you. :) Will just continue watching the `guzzle/guzzle-services` repo as there seems to be a ticket also related to the same issue. Thanks @jwcobb!

**Comment by lucasatace** [comment]
Is there any update on this? I am running into the same issue as @sonnygauran. My project requires that I have both `guzzlehttp/guzzle` and `ticketevolution/ticketevolution-php` integrated.

**Comment by jwcobb** [comment]
There has been no updates to `guzzle/guzzle-services` to make it compatible with `guzzlehttp/guzzle:^6.0`. I'm hoping to see @jeremeamia at the AzPHP meeting later this month so hopefully I can get an idea if `guzzle/guzzle-services` & `guzzle/commands` will be updated to support 6+. If not, this project would need to be rewritten to remove those dependencies.

**Comment by jeremeamia** [comment]
I started working on the commands package already: https://github.com/guzzle/command/tree/guzzle6

**Comment by N30** [comment]
I am not having issues installing with Laravel 5.2, but I am having some related issues, I opened a new issue.

**Comment by jwcobb** [comment]
@sonnygauran Check out the new dev-4.0.0 branch which upgrades to Guzzle 6.2

**Comment by jwcobb** [comment]
Version 4.0 released uses Guzzle 6.2
