### ISSUE TITLE
500 [reason phrase] Internal Server Error

### ISSUE THREAD

**Issue by ajvanhoo** [ticketevolution/ticketevolution-php#128]
Hi,

tried to create an order with existing customer (address, credit card and phone are stored in TE) but the API gives me 500 error. 
I followed the sample order creation from "Orders / Create" page on your website, but no luck.

I used event_id = 750000

This is the array that I'm passing to createOrders function:

```json
Array
(
    [orders] => Array
        (
            [0] => stdClass Object
                (
                    [shipped_items] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [items] => Array
                                        (
                                            [0] => stdClass Object
                                                (
                                                    [price] => 8
                                                    [ticket_group_id] => 244917353
                                                    [quantity] => 1
                                                    [signature] => 1eL0OuUJMxvqinb+r90cttcDZAaPhM0rnhyuQE4e7Lg=--03dWMAfHf8gwp8GCfJnWXQ==
                                                )

                                        )

                                )

                            [phone_number_id] => 284413
                            [service_type] => LEAST_EXPENSIVE
                            [type] => FedEx
                            [address_id] => 625391
                            [ship_to_name] => Test Customer
                        )

                    [payments] => Array
                        (
                            [0] => stdClass Object
                                (
                                    [type] => credit_card
                                    [amount] => 88.00
                                    [credit_card_id] => 18945
                                )

                        )

                    [billing_address_id] => 625391
                    [created_by_ip_address] => 12.34.56.78
                    [instructions] => This is just a test instructions
                    [seller_id] => **** (office number from sandbox)
                    [client_id] => 158603
                )

        )
)
```

Tried with the simple array and eticket also but still getting the same error.

Am I missing something in this array or something else is the problem ?
Thanks!

**Comment by jwcobb** [comment]
Any chance you can provide that in PHP or JSON?

**Comment by ajvanhoo** [comment]
Hello,
if you mean php code which reproduces this array, here it is:
`
        $item = new \stdClass();
        $item->price = $ticketGroupPrice;
        $item->ticket_group_id = $ticketGroupId;
        $item->quantity = 1;
        $item->signature = $ticketGroupSignature;

        $payments = new \stdClass();
        $payments->type = 'credit_card';
        $payments->amount = '88.00';
        $payments->credit_card_id = $creditCardId;

        $t = new \stdClass();
        $t->items[] = $item;

        $order1 = new \stdClass();
        $order1->shipped_items[] = $t;
        $order1->shipped_items['phone_number_id'] = $clientPhoneNumberId;
        $order1->shipped_items['service_type'] = 'LEAST_EXPENSIVE';
        $order1->shipped_items['type'] = 'FedEx';
        $order1->shipped_items['address_id'] = $ship_address_id;
        $order1->shipped_items['ship_to_name'] = 'Test Customer';

        $order1->payments[] = $payments;
        $order1->billing_address_id = $ship_address_id;
        $order1->created_by_ip_address = '172.222.215.544';
        $order1->instructions = 'This is just a test instructions';
        #$order1->billing_address = $billingAddress;

        $order1->seller_id = $seller_id;
        $order1->client_id = $client_id;
        $orderDetails['orders'][] = $order1;

        $results = $apiClient->createOrders($orderDetails);`

All those variables are from API calls that actually retrieves data.

**Comment by jwcobb** [comment]
What you have isn't creating the right JSON. You can always check it by dumping the a `json_encode()` of what you have and comparing to the examples in teh documentation.

Try this
```php
$item = new \stdClass();
$item->price = 30;
$item->ticket_group_id = 123456789;
$item->quantity = 1;
$item->signature = 'aaaaaaaaaaaaaaaaaaaaaa';

$payments = new \stdClass();
$payments->type = 'credit_card';
$payments->amount = '88.00';
$payments->credit_card_id = 111111;


$order1 = new \stdClass();
$order1->shipped_items[0]['items'] = $item;
$order1->shipped_items[0]['phone_number_id'] = 222222;
$order1->shipped_items[0]['service_type'] = 'LEAST_EXPENSIVE';
$order1->shipped_items[0]['type'] = 'FedEx';
$order1->shipped_items[0]['address_id'] = 333333333;
$order1->shipped_items[0]['ship_to_name'] = 'Test Customer';

$order1->payments[] = $payments;
$order1->billing_address_id = 4444444444;
$order1->created_by_ip_address = '172.222.215.544';
$order1->instructions = 'This is just a test instructions';
#$order1->billing_address = $billingAddress;

$order1->seller_id = 5555555;
$order1->client_id = 66666666;
$orderDetails['orders'][] = $order1;

var_dump(json_encode($orderDetails));
```

**Comment by ajvanhoo** [comment]
Hi,
it's still showing me:

Error executing command: Server error response [url] https://api.sandbox.ticketevolution.com/v9/orders [status code] 500 [reason phrase] Internal Server Error

**Comment by jwcobb** [comment]
This is not an issue with the ticketevolution-php library. This is an issue with the data you are sending not being formed properly. You should review the documentation and make sure your data is properly formatted.

**Comment by ajvanhoo** [comment]
Well, you sent me the test data, turns out that those are incorrect too ?
Can you send me the right array which I should pass to createOrders functions ?
Thanks
