### ISSUE TITLE
Service Unavailable

### ISSUE THREAD

**Issue by stojko75** [ticketevolution/ticketevolution-php#131]
We have guest checkout on our site. After guest review his order and confirm it, we start with process of creating order on TicketEvolution. First we create user, get his Id from Ticket Evolution, create address, phone number and other elements of order. On the end we create order and submit it to TiEvo.
However, sometimes we receive "Service unavailable" error??? After few times of trying with same data, order is created?! 
Sometimes the error is in process of adding phonenumber to client, sometimes when adding address to client and sometimes it just go fine and return order Id.
However, there's no such problem with registered users. When they buy, we already have tievoId for client, address, phonenumber created in registration process. 
What's the reason and how to handle this? We use ticketevolution-php, is there some additional class or something we need to use? Is it possible that it has something with number of requests to TiEvo server?! or something?

This is from debug logger: 
<h2>Service Unavailable</h2> <p>The service is temporarily unavailable. Please try again later.</p> </body> </html>  -------- Server error response [url] https://api.sandbox.ticketevolution.com/v9/clients/159245/phone_numbers [status code] 500 [reason phrase] Internal Server Error {"request":"[object] (GuzzleHttp\\Message\\Request: POST /v9/clients/159245/phone_numbers HTTP/1.1\r\nHost: api.sandbox.ticketevolution.com\r\nUser-Agent: ticketevolution-php/3.0.4 Guzzle/5.3.0 curl/7.36.0 PHP/5.5.12\r\nContent-Type: application/json\r\nContent-Length: 42\r\n.....{\"phone_numbers\":[{\"number\":\"015352344\"}]})","response":"[object] (GuzzleHttp\\Message\\Response: HTTP/1.1 500 Internal Server Error\r\nDate:

**Comment by jwcobb** [comment]
A "Service Unavailable" is due to something on the server, not the ticketevolution-php library. You could add Guzzle's retry subscriber https://github.com/guzzle/retry-subscriber if you wanted to.

**Comment by stojko75** [comment]
I will. Is that normal and expected? What's the reason for that?

**Comment by jwcobb** [comment]
It isn't normal, but it is possible. Sometimes you might see this during a deploy.
