### ISSUE TITLE
ticket_utils_id

### ISSUE THREAD

**Issue by stojko75** [ticketevolution/ticketevolution-php#137]
What's the best way to get ticket_utils_id by api, taking into account that we use tevo-harvester and local database?

If I need to use /v9/events/:event_id endpoint then whats the point of using local events table?

**Comment by jwcobb** [comment]
`ticket_utils_id` has been deprecated and is not provided any more.

**Comment by stojko75** [comment]
Is there some other seating chart system supported by you, except one
provided by TE?

**Comment by jwcobb** [comment]
Seating charts have nothing to do with this library. Please direct your question to sellersupport @ ticketevolution.com
