### ISSUE TITLE
retrieve order 

### ISSUE THREAD

**Issue by ashishsharma45** [ticketevolution/ticketevolution-php#144]
Hi,

are you making all order listing ? please help how to?

thanks

**Comment by jwcobb** [comment]
Can you explain what you mean by “retrieve order for client functionality”?

**Comment by ashishsharma45** [comment]
Can you tell how we can fetch all orders with correct details in order to properly display them in sites admin panel?
Currently we are fetching orders using v9 api with buyer id = 6 as mentioned in docs.
