### ISSUE TITLE
Unable to test the createOrder feature in sandbox

### ISSUE THREAD

**Issue by optest** [ticketevolution/ticketevolution-php#162]
Hello,
I am trying to test the creatOrder API in the sandbox but getting the below error
{"error":"Something went wrong with your request. Details about the error: no implicit conversion of String into Integer"}

with this error i am unable to identify the actual issue
please help me out

**Comment by jwcobb** [comment]
I'd be happy to help but need to see the details of your request in order to help troubleshoot.

**Comment by optest** [comment]
I am using the php for accessing this APIs but having trouble only with the order API

**Comment by optest** [comment]
below is the request 

Array
(
    [orders] => Array
        (
            [seller_id] => 1129
            [shipping] => 0
            [service_fee] => 0
            [tax] => 0
            [additional_expense] => 0
            [client_id] => 205962
            [payments] => Array
                (
                    [0] => Array
                        (
                            [type] => offline
                        )

                )

            [items] => Array
                (
                    [0] => Array
                        (
                            [ticket_group_id] => 310400029
                            [quantity] => 1
                            [price] => 5
                        )

                )

            [shipping_address] => Array
                (
                    [label] => upendra
                    [name] => upendra Goswami
                    [company] => bv
                    [street_address] => Array
                        (
                            [0] => vbnm,
                            [1] => sadasdsadas
                            [2] => asdsadsadsa
                        )

                    [extended_address] => 
                    [locality] => ghm
                    [region] => California
                    [postal_code] => 90001
                    [country_code] => US
                )

            [billing_address] => Array
                (
                    [label] => upendra
                    [name] => upendra Goswami
                    [company] => bv
                    [street_address] => Array
                        (
                            [0] => vbnm,
                            [1] => sadasdsadas
                            [2] => asdsadsadsa
                        )

                    [extended_address] => 
                    [locality] => ghm
                    [region] => California
                    [postal_code] => 90001
                    [country_code] => US
                )

        )

)

**Comment by jwcobb** [comment]
This does not appear to be an issue with the PHP Library itself. Please contact technicalsupport@ticketevolution.com for more help. Please include a code snippet of your order building process so I can help you further.

**Comment by suraj-singhsu** [comment]
Hello @jwcobb & @optest 

Can you please let me know the solution of this issues?
