### ISSUE TITLE
Replace Methods

### ISSUE THREAD

**Issue by cpgb85** [ticketevolution/ticketevolution-php#174]
My client got a notification some API requests we are using are not longer supported, this has to do with ticket_groups getting replaced with listings.  There is no explanation on how to change this while using this library, and there is no way to know currently what data gets returned.  

Is there any documentation for this library?

**Comment by jwcobb** [comment]
Support for `listings()` and `showListing()` was [added in December 2021](https://github.com/ticketevolution/ticketevolution-php/blob/master/CHANGELOG.md#429-december-8-2021). You likely just need to update any usage of `listTicketGroups()` to `listings()` and `showTicketGroup()` to `showListing()`. You may need to remove some unsupported parameters (`lightweight`, `ticket_list`, `include_tevo_section_mappings`, `format`) from any `listings()` requests.

This library also has a [Documentation.md](https://github.com/ticketevolution/ticketevolution-php/blob/master/Documentation.md) file.

**Comment by cpgb85** [comment]
I wouldn't say this is resolved. The documentation on the website is a mess.  

I would assume I need to update my version correct?

**Comment by jwcobb** [comment]
> The documentation on the website is a mess.

I'm not sure to which documentation you are referring but if it is the [Documentation.md file](https://github.com/ticketevolution/ticketevolution-php/blob/master/Documentation.md) I’d gladly accept a PR with your suggested improvements.

> I would assume I need to update my version correct?

I do not know what version you are using so I can not be sure if you need to update.
