### ISSUE TITLE
Symfony error

### ISSUE THREAD

**Issue by cpgb85** [ticketevolution/ticketevolution-php#175]
I downloaded the most recent version of this library and it won't output anything but an error when running any method. 
I attached an image of what I am inputting, and what it is outputting.

![image](https://user-images.githubusercontent.com/21691341/221677810-33118ff4-12fb-4348-9e71-ad5ed9241265.png)

![image](https://user-images.githubusercontent.com/21691341/221678034-e8db4396-190f-4417-bb3d-8f5ae0815741.png)

**Comment by cpgb85** [comment]
I haven't heard back. Any status on this?

**Comment by jwcobb** [comment]
Check out the new 5.0.0 branch and see if that works for you.

**Comment by cpgb85** [comment]
How do I do that with composer?

**Comment by jwcobb** [comment]
I believe you can do
```
composer require ticketevolution/ticketevolution-php@dev-5.0.0
```

**Comment by cpgb85** [comment]
![image](https://user-images.githubusercontent.com/21691341/223209395-f4a4c065-060c-45aa-a219-d8bff8d72cff.png)

**Comment by jwcobb** [comment]
You will need to set your minimum stability to `dev`

**Comment by cpgb85** [comment]
forgive my ignorance, where?

**Comment by cpgb85** [comment]
figured it out. it doesn't seem to work still.  Why is symfony causing this problem?

**Comment by cpgb85** [comment]
do you have any idea what could be causing this problem? i've tried with different versions of PHP, it all returns the same problem.

**Comment by jwcobb** [comment]
I don't. Perhaps you could share more information or a small sample project where we could replicate your issue,

**Comment by cpgb85** [comment]
I provided a screenshot above of the only thing I am doing.   The problem doesn't occur until I trigger a method of the class.  In this case, it's "$te->ShowOffice".  My client currently uses this library, so I'm installing it on a local server running PHP version 8.2.0 currently. 

I used composer to install this library like the github page explained. Are you a ticketevolution employee?

**Comment by cpgb85** [comment]
Is there any status on this?

**Comment by jwcobb** [comment]
I don't really have enough more information to troubleshoot any further. Your screenshot is not enough. It might help if you posted your `composer.json` file.

**Comment by cpgb85** [comment]
Sure,  here it is:

`{
    "name": "caleb/eventusa",
    "require": {
        "ticketevolution/ticketevolution-php": "^4.4"
    }
}
`

Not much was inserted into it when installing this library.

**Comment by cpgb85** [comment]
I figured it out. Oh my gosh.  in the programming i was using, the api version was just "9".  it's supposed to be "v9".

**Comment by jwcobb** [comment]
I'm glad you figured it out!
