### ISSUE TITLE
Older version installing

### ISSUE THREAD

**Issue by krishna220414** [ticketevolution/ticketevolution-php#177]
I am using laravel version 10.48 I have just setup a new laravel project and when i am running this command
"composer require ticketevolution/ticketevolution-php"
the ticketevolution version 2.2.2 is installing
![Screenshot 2024-07-02 181231](https://github.com/ticketevolution/ticketevolution-php/assets/99238436/26a4a112-fd5e-4dbb-bdb3-642634cf3548)
 i dont know why this is happening why older version is installing in which there is no file of c;lient in it so how can i use this 
 use TicketEvolution\Client as TEvoClient; when the file is not present please resolve my issue

**Comment by jwcobb** [comment]
Quoting from https://getcomposer.org/doc/articles/versions.md#caret-version-range-
>The `^` operator behaves very similarly, but it sticks closer to semantic versioning, and will always allow non-breaking updates. For example `^1.2.3` is equivalent to `>=1.2.3 <2.0.0` as none of the releases until 2.0 should break backwards compatibility.

Your Composer settings are constraining you to the equivalent of `>=2.2.0 <3.0.0`.
