### ISSUE TITLE
Create Order

### ISSUE THREAD

**Issue by villav** [ticketevolution/ticketevolution-php#3]
Hi,

are you making create order functionality? is there any ETA?

thanks

**Comment by Bodia1999** [comment]
cannot create credit card through sandbox ( error "unprocessable entity”)

**Comment by jwcobb** [comment]
> cannot create credit card through sandbox ( error "unprocessable entity”)

@Bodia1999 If your Sandbox account is configured with Braintree please open a new Issue with some details. If you are unsure if your Sandbox account is configured with Braintree please reach out to your representative to have that done.

**Comment by Bodia1999** [comment]
How to configure my sandbox with Braintree?
This is my entity request

{\n" +
        "  \"credit_cards\": [\n" +
        "    {\n" +
        "      \"label\": \"Chase Sapphire Reserve\",\n" +
        "      \"name\": \"Ned Flanders\",\n" +
        "      \"number\": \"4111111111111111\",\n" +
        "      \"expiration_month\": \"12\",\n" +
        "      \"expiration_year\": \"2021\",\n" +
        "      \"verification_code\": \"789\",\n" +
        "      \"address_id\": 661989,\n" +
        "      \"phone_number_id\": 306540,\n" +
        "      \"ip_address\": \"37.235.140.72\"\n" +
        "    }\n" +
        "  ]\n" +
        "}

And it is response
{
"code": 500,
"message": "422 Unprocessable Entity"
}
I will very grateful if you help me to create credit card and give some
info about creating create order also

вт, 13 серп. 2019 о 23:02 J Cobb <notifications@github.com> пише:

**Comment by Bodia1999** [comment]
How can I get credentials to sandbox account but I have only token and
secret key
I need to finish my project, maybe I can to register to your sandbox


чт, 15 серп. 2019 о 13:34 Bohdan Papizhanskiy <bogdanpapizhanskiy@gmail.com>
пише:

**Comment by jwcobb** [comment]
@Bodia1999 Please reach out to your contact at Ticket Evolution regarding your account. This does not appear to be an issue with the library, nor should it be appended on to a previously closed issue.

**Comment by Bodia1999** [comment]
I don't have an answer in "onboarding" about account for week
My ticket id is 6842
Can you help me?
чт, 15 серп. 2019 о 21:23 J Cobb <notifications@github.com> пише:

**Comment by jwcobb** [comment]
@Bodia1999 Please reach out to your contact at Ticket Evolution regarding your account. This does not appear to be an issue with the library, nor should it be appended on to a previously closed issue.
